# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\cmake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Code\CPP\Proj\project3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Code\CPP\Proj\project3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\cmake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\cmake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\CPP\Proj\project3\CMakeFiles D:\Code\CPP\Proj\project3\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\CPP\Proj\project3\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project3

# Build rule for target.
project3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 project3
.PHONY : project3

# fast build rule for target.
project3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/build
.PHONY : project3/fast

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/main.cpp.s
.PHONY : main.cpp.s

src/AGXKit.obj: src/AGXKit.cpp.obj
.PHONY : src/AGXKit.obj

# target to build an object file
src/AGXKit.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/AGXKit.cpp.obj
.PHONY : src/AGXKit.cpp.obj

src/AGXKit.i: src/AGXKit.cpp.i
.PHONY : src/AGXKit.i

# target to preprocess a source file
src/AGXKit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/AGXKit.cpp.i
.PHONY : src/AGXKit.cpp.i

src/AGXKit.s: src/AGXKit.cpp.s
.PHONY : src/AGXKit.s

# target to generate assembly for a file
src/AGXKit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/AGXKit.cpp.s
.PHONY : src/AGXKit.cpp.s

src/Battery.obj: src/Battery.cpp.obj
.PHONY : src/Battery.obj

# target to build an object file
src/Battery.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Battery.cpp.obj
.PHONY : src/Battery.cpp.obj

src/Battery.i: src/Battery.cpp.i
.PHONY : src/Battery.i

# target to preprocess a source file
src/Battery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Battery.cpp.i
.PHONY : src/Battery.cpp.i

src/Battery.s: src/Battery.cpp.s
.PHONY : src/Battery.s

# target to generate assembly for a file
src/Battery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Battery.cpp.s
.PHONY : src/Battery.cpp.s

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Chassis.obj: src/Chassis.cpp.obj
.PHONY : src/Chassis.obj

# target to build an object file
src/Chassis.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Chassis.cpp.obj
.PHONY : src/Chassis.cpp.obj

src/Chassis.i: src/Chassis.cpp.i
.PHONY : src/Chassis.i

# target to preprocess a source file
src/Chassis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Chassis.cpp.i
.PHONY : src/Chassis.cpp.i

src/Chassis.s: src/Chassis.cpp.s
.PHONY : src/Chassis.s

# target to generate assembly for a file
src/Chassis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Chassis.cpp.s
.PHONY : src/Chassis.cpp.s

src/Display.obj: src/Display.cpp.obj
.PHONY : src/Display.obj

# target to build an object file
src/Display.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Display.cpp.obj
.PHONY : src/Display.cpp.obj

src/Display.i: src/Display.cpp.i
.PHONY : src/Display.i

# target to preprocess a source file
src/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Display.cpp.i
.PHONY : src/Display.cpp.i

src/Display.s: src/Display.cpp.s
.PHONY : src/Display.s

# target to generate assembly for a file
src/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Display.cpp.s
.PHONY : src/Display.cpp.s

src/Gyroscope.obj: src/Gyroscope.cpp.obj
.PHONY : src/Gyroscope.obj

# target to build an object file
src/Gyroscope.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Gyroscope.cpp.obj
.PHONY : src/Gyroscope.cpp.obj

src/Gyroscope.i: src/Gyroscope.cpp.i
.PHONY : src/Gyroscope.i

# target to preprocess a source file
src/Gyroscope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Gyroscope.cpp.i
.PHONY : src/Gyroscope.cpp.i

src/Gyroscope.s: src/Gyroscope.cpp.s
.PHONY : src/Gyroscope.s

# target to generate assembly for a file
src/Gyroscope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Gyroscope.cpp.s
.PHONY : src/Gyroscope.cpp.s

src/LIDAR.obj: src/LIDAR.cpp.obj
.PHONY : src/LIDAR.obj

# target to build an object file
src/LIDAR.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/LIDAR.cpp.obj
.PHONY : src/LIDAR.cpp.obj

src/LIDAR.i: src/LIDAR.cpp.i
.PHONY : src/LIDAR.i

# target to preprocess a source file
src/LIDAR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/LIDAR.cpp.i
.PHONY : src/LIDAR.cpp.i

src/LIDAR.s: src/LIDAR.cpp.s
.PHONY : src/LIDAR.s

# target to generate assembly for a file
src/LIDAR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/LIDAR.cpp.s
.PHONY : src/LIDAR.cpp.s

src/SmartCar.obj: src/SmartCar.cpp.obj
.PHONY : src/SmartCar.obj

# target to build an object file
src/SmartCar.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/SmartCar.cpp.obj
.PHONY : src/SmartCar.cpp.obj

src/SmartCar.i: src/SmartCar.cpp.i
.PHONY : src/SmartCar.i

# target to preprocess a source file
src/SmartCar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/SmartCar.cpp.i
.PHONY : src/SmartCar.cpp.i

src/SmartCar.s: src/SmartCar.cpp.s
.PHONY : src/SmartCar.s

# target to generate assembly for a file
src/SmartCar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/SmartCar.cpp.s
.PHONY : src/SmartCar.cpp.s

src/Student.obj: src/Student.cpp.obj
.PHONY : src/Student.obj

# target to build an object file
src/Student.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Student.cpp.obj
.PHONY : src/Student.cpp.obj

src/Student.i: src/Student.cpp.i
.PHONY : src/Student.i

# target to preprocess a source file
src/Student.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Student.cpp.i
.PHONY : src/Student.cpp.i

src/Student.s: src/Student.cpp.s
.PHONY : src/Student.s

# target to generate assembly for a file
src/Student.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Student.cpp.s
.PHONY : src/Student.cpp.s

src/Wheel.obj: src/Wheel.cpp.obj
.PHONY : src/Wheel.obj

# target to build an object file
src/Wheel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Wheel.cpp.obj
.PHONY : src/Wheel.cpp.obj

src/Wheel.i: src/Wheel.cpp.i
.PHONY : src/Wheel.i

# target to preprocess a source file
src/Wheel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Wheel.cpp.i
.PHONY : src/Wheel.cpp.i

src/Wheel.s: src/Wheel.cpp.s
.PHONY : src/Wheel.s

# target to generate assembly for a file
src/Wheel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/src/Wheel.cpp.s
.PHONY : src/Wheel.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... project3
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... src/AGXKit.obj
	@echo ... src/AGXKit.i
	@echo ... src/AGXKit.s
	@echo ... src/Battery.obj
	@echo ... src/Battery.i
	@echo ... src/Battery.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Chassis.obj
	@echo ... src/Chassis.i
	@echo ... src/Chassis.s
	@echo ... src/Display.obj
	@echo ... src/Display.i
	@echo ... src/Display.s
	@echo ... src/Gyroscope.obj
	@echo ... src/Gyroscope.i
	@echo ... src/Gyroscope.s
	@echo ... src/LIDAR.obj
	@echo ... src/LIDAR.i
	@echo ... src/LIDAR.s
	@echo ... src/SmartCar.obj
	@echo ... src/SmartCar.i
	@echo ... src/SmartCar.s
	@echo ... src/Student.obj
	@echo ... src/Student.i
	@echo ... src/Student.s
	@echo ... src/Wheel.obj
	@echo ... src/Wheel.i
	@echo ... src/Wheel.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

